name: Node.js CI + Auto Approve

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  pull_request_target: # 🔥 자동 승인을 위한 추가 이벤트
    types: [opened, reopened, synchronize]
  workflow_dispatch:

permissions:
  actions: write
  pull-requests: read
  contents: read # 코드 체크아웃을 위해 추가

jobs:
  # ----------------------------------
  # 1. 자동 승인 작업 (신규 기여자용)
  # ----------------------------------
  auto-approve:
    if: github.event_name == 'pull_request_target' # PR 대상 이벤트에서만 실행
    runs-on: ubuntu-latest
    steps:
      - name: Approve First-Time Contributors
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          RUN_IDS=$(gh api "/repos/${{ github.repository }}/actions/runs?event=pull_request&pull_request=$PR_NUMBER" --jq '.workflow_runs[] | select(.status == "waiting") | .id')
          for RUN_ID in $RUN_IDS; do
            echo "Approving Run ID: $RUN_ID"
            gh api -X POST "/repos/${{ github.repository }}/actions/runs/$RUN_ID/approve"
          done

  # ----------------------------------
  # 2. 기존 빌드/테스트 작업 (모든 PR에 적용)
  # ----------------------------------
  build-and-test:
    needs: auto-approve # 자동 승인 후 실행
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # v3 → v4로 업그레이드

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4 # v3 → v4로 업그레이드
        with:
          node-version: 22
          cache: "npm" # 🔥 npm 캐싱 추가 (빌드 속도 향상)

      - name: Install dependencies
        run: npm ci # npm install → npm ci로 변경 (정확한 버전 보장)

      - name: Run tests
        run: npm test
